---
env:
  es6: true
  browser: true
  node: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  operator-linebreak: off
  implicit-arrow-linebreak: off
  no-nested-ternary: off
  prefer-template: off
  no-return-assign: off
  no-confusing-arrow: off
  indent:
  - error
  - 2
  - SwitchCase: 1
    ignoredNodes:
    - ConditionalExpression *
    - JSXElement *
  arrow-parens:
  - error
  - as-needed
  comma-dangle:
  - error
  - always-multiline
  no-underscore-dangle:
  - error
  - allow:
    - _id
    - __REDUX_DEVTOOLS_EXTENSION_COMPOSE__
  no-unused-expressions:
  - error
  - allowTaggedTemplates: true
    allowShortCircuit: true
    allowTernary: true
  object-curly-newline:
  - error
  - multiline: true
    consistent: true
  function-paren-newline:
  - error
  - consistent
  no-trailing-spaces:
  - error
  - skipBlankLines: true
    ignoreComments: true
  jsx-a11y/href-no-hash: off
  jsx-a11y/media-has-caption: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/interactive-supports-focus: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/label-has-for: off
  jsx-a11y/anchor-has-content: off
  react/jsx-one-expression-per-line: off
  react/jsx-first-prop-new-line: off
  react/jsx-indent-props: off
  react/jsx-indent: off
  react/jsx-props-no-spreading: off
  react/jsx-max-props-per-line: off
  react/jsx-filename-extension: off
  react/jsx-wrap-multilines: off
  react/no-did-mount-set-state: off
  react/forbid-prop-types: off
  react/destructuring-assignment: off
  react/no-danger: off
  react/prop-types: off
  react-hooks/exhaustive-deps: off
