[build]
  publish = "public"
  command = "yarn build"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "https://oasa.netlify.com"
  to = "http://oasa.netlify.com"
  status = 301
  force = true
