[build]
  command = "yarn build"
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/api/*"
  to = "http://telematics.oasa.gr/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }
[[redirects]]
  from = "https://oasa.netlify.com/*"
  to = "https://oasa.bonsa.io/:splat"
  status = 301
  force = true
